language: generic

before_install:
   - curl -L https://sourceforge.net/projects/zsh/files/latest/download > zsh.tar.xz
   - tar -xvJf zsh.tar.xz
   - cd zsh*/
   - ./configure --prefix="${HOME}/.local"
   - make
   - make install
   - cd -
   - rm -fr zsh*

env:
  - SHELL=sh
  - SHELL=bash
  - SHELL="zsh -y"

install:
  - curl -L https://github.com/AlexisBRENON/god-bless-git/archive/master.tar.gz > gbg.tar.gz
  - tar -xvzf gbg.tar.gz
  - . ./god-bless-git-master/god_bless_git.sh

before_script:
  - PATH="$HOME/.local/bin:$PATH"

script:
  - make "TEST_SHELL=${SHELL}" tests

after_failure:
  - make "TEST_SHELL=${SHELL} -x" tests

