#! /usr/bin/env zsh
#
# TODO
#
# Authors:
#   Alexis BRENON
#

PROMPT_ALEXIS_PATH="$(dirname "$(command -V $0 | sed -Ee 's#.* from (/.*/'$0').*#\1#')")"
. "${PROMPT_ALEXIS_PATH}/init.sh"

function prompt_alexis_setup {
  prompt_opts=(cr percent subst)

  prompt_alexis_posix_setup $@

  # Load required functions.
  autoload -Uz add-zsh-hook
  add-zsh-hook precmd prompt_alexis_precmd

  export _prompt_alexis_async_refresh_command="zle && zle reset-prompt && print ''"
  # Define prompts.
  PROMPT='${$(prompt_alexis_build_prompt)}${editor_info[keymap]}'
  RPROMPT=''
}

function prompt_alexis_preview {
  local +h PROMPT=''
  local +h RPROMPT=''
  local +h SPROMPT=''

  editor-info 2>/dev/null
  prompt_preview_theme 'alexis'
}

function prompt_alexis_help {
  prompt_alexis_posix_help
}

prompt_alexis_setup "$@"
