#! /bin/zsh
#
# TODO
#
# Authors:
#   Alexis BRENON
#

_shell_state="$(set +o | grep -v -e '+o')"
set -euo pipefail

# #########################################################
#
# Utilities
#
# #########################################################

get_absolute_dirname() {
    SOURCE="$1"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        [ "$SOURCE" != "/*" ] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    ( cd -P "$( dirname "$SOURCE" )" && pwd )
    unset DIR
    unset SOURCE
}


# #########################################################
#
# Call detector
#
# #########################################################

sterope_call=""
sterope_main="sterope_prompt"
if [ -z "${sterope_call}" ]; then # Try to guess call type (invokation vs. sourcing)
    if [ -n "${ZSH_VERSION:-}" ]; then # Z Shell
        eval_context="${ZSH_EVAL_CONTEXT:-}"
        if [ \
            "$(echo "${eval_context}" | rev | cut -d: -f1 | rev)" = \
            "file" ]; then
            sterope_call="source"
        else
            sterope_call="invoke"
        fi
        sterope_main="$0"
        unset eval_context
    elif [ -n "${BASH_VERSION:-}" ]; then # Bash
        if [ "$(basename "${0:-}")" = "${sterope_main}" ]; then
            sterope_call="invoke"
            sterope_main="$0"
        else
            sterope_call="source"
            # shellcheck disable=SC2039
            sterope_main="${BASH_SOURCE[0]}"
        fi
    else # Other shells
        if [ "$(basename "${0:-}")" = "${sterope_main}" ]; then
            sterope_call="invoke"
            sterope_main="$0"
        else
            sterope_call="source"
        fi
    fi
fi

STEROPE_ROOT="${STEROPE_ROOT:-$(get_absolute_dirname "${sterope_main}")}"
sterope_main="${STEROPE_ROOT}/$(basename "${sterope_main}")"

# #########################################################
#
# Call entry points
#
# #########################################################

if [ ! -r "${sterope_main}" ]; then
    error "Unable to get Sterope base directory." >&2
    error "Please define the STEROPE_ROOT environment variable" \
        "to the base directory, before invoking script." >&2
else
    export STEROPE_ROOT
    export STEROPE_VERSION="0.0.1"
    if [ "${sterope_call}" = "invoke" ]; then
        # Script invoked as command
        # shellcheck source=./main/invoke.sh
        . "${STEROPE_ROOT}/main/invoke.sh"
    elif [ "${sterope_call}" = "source" ]; then
        # Script sourced
        # shellcheck source=./main/source.sh
        . "${STEROPE_ROOT}/main/source.sh"
    else
        echo "Unable to determine invokation type." >&2
    fi
fi

set +euo pipefail
eval "${_shell_state}"
unset _shell_state

